name: ci-exec
description: Excute a command and store its output

inputs:
  run:
    description: Command to execute
    required: true
  working-directory:
    description: Command working directory
    required: false
  shell:
    description: Shell used to run command
    required: false
    default: bash

outputs:
  stdout:
    description: Output of the command
  stderr:
    description: Error of the command
runs:
  using: 'node16'
  main: 'dist/index.js'
